### ISSUE TITLE
Display LiveNow Streams

### ISSUE THREAD

**Issue by milenark** [TUM-Dev/gocast_mobile#181]
#### Todo: 

- [x] display live streams instead of currently live courses under 'Live Now'
- [x] navigation is directly to the livestream onclick, not to the course
- [x] Correct navigation path of "see more" button (should not to go MyCourses) 

#### Future refinements:   
- UI could maybe be improved at some point. 
- For now the 'see more' button was removed - do we need to add it with a corresponding separate view for all live streams? 

#### Progress: 
<img width="300" alt="Screenshot 2024-01-08 at 16 57 20" src="https://github.com/TUM-Dev/gocast_mobile/assets/84514915/d5818776-4567-42ed-953c-14e19828f226">
