### ISSUE TITLE
[UI] Adjust UI according to feedback 1

### ISSUE THREAD

**Issue by milenark** [TUM-Dev/gocast_mobile#227]
### TODO
React to Benedicts first feedback. 

### Feedback: 
- [ ] “Home”-Tab: You’ve done a great job! I really like the overall structure of this screen. It’s clear and you can quickly understand where to find what.
- [ ] For the “Live Now” tiles, I would recommend that you think again about whether you really need the button for the room in the home view. On the one hand, you have a button on another button - which can lead to accidental entries - on the other hand, the idea behind your app is that you don’t have to search for the room but can watch the lecture from anywhere. Don’t get me wrong. The feature is still cool - but I think it would be better on the details page. I also think that the ID of the course (here e.g. IN0009) is a bit lost in the upper left corner. I have attached an alternative suggestion for you
- [ ] “Settings”-View: Be sure to check your paddings again here. These are not yet completely uniform. Maybe you can make the whole thing look a bit more like iOS. But I know that sometimes it’s not that easy in Flutter. To ensure that your app corresponds to the Apple HIGs in this respect, I would also recommend that you adopt the system-wide theming in your app by default. So if iOS is in dark mode, your app will also be in dark mode. If you still want to set this independently, you could introduce a third state “System” in the Dark Mode settings. But then you would probably have to replace the toggle with another input option.
